name: latlong
description: Lightweight library for common latitude and longitude calculation
_authors:
  - Mike Mitterer <office@mikemitterer.at>
  - David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/MikeMitterer/dart-latlong
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.19.0
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.16.8
