name: latlong
description: Lightweight library for common latitude and longitude calculation
authors:
  - Mike Mitterer <office@mikemitterer.at>
  - David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/MikeMitterer/dart-latlong
version: 0.6.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ">=0.15.0 <1.0.0"
  validate: ^1.0.0

dev_dependencies:
  pedantic:
  test:
