name: latlong
description: Lightweight library for common latitude and longitude calculation
authors:
  - Mike Mitterer <office@mikemitterer.at>
  - David PHAM-VAN <dev.nfet.net@gmail.com>
homepage: https://github.com/MikeMitterer/dart-latlong
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
